FROM node:18-alpine

WORKDIR /app

# Install dependencies only when needed
COPY package.json package-lock.json* ./
RUN npm install

# Copy next.config.js and other config files
COPY next.config.ts .
COPY tsconfig.json .
COPY tailwind.config.js .
COPY postcss.config.mjs .

# Copy source code
COPY src ./src
COPY public ./public

# Expose NextJS development port
EXPOSE 3000

# Command is specified in docker-compose.dev.yml
